import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import {
  getTopRated,
  getNowPlaying,
  getPopular,
  getUpcoming,
} from "@/redux/moviesSlice";
import InTheatres from "@/components/InTheatres";
import Row from "@/components/Row";

export default function Home() {
  const topRatedMovies = useSelector((state) => state.topRated);
  console.log("topRatedMovies", topRatedMovies);

  const nowPlayingMovies = useSelector((state) => state.nowPlaying);
  // console.log("nowPlayingMovies", nowPlayingMovies);

  const popularMovies = useSelector((state) => state.popular);
  // console.log("popularMovies", popularMovies);

  const upcomingMovies = useSelector((state) => state.upcoming);
  // console.log("upcomingMovies", upcomingMovies);

  const dispatch = useDispatch();
  // Call all types of movie data
  useEffect(() => {
    dispatch(getTopRated());
    dispatch(getNowPlaying());
    dispatch(getPopular());
    dispatch(getUpcoming());
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>Movies UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ width: "100%", minHeight: "100vh", position: "relative" }}>
        <InTheatres nowPlayingMovies={nowPlayingMovies} />
        <Row movies={upcomingMovies} name={"Upcoming"}/>
        <Row movies={topRatedMovies} name={"Top Rated"}/>
        <Row movies={popularMovies} name={"Popular"}/>
      </main>
    </>
  );
}
